### ISSUE TITLE
Update link in README

### ISSUE THREAD

**Issue by kbarros** [NREL/alfabet#1]
The `README.md` file includes the text  `[ml.nrel.gov](ml.nrel.gov)`. This is actually a broken link (missing `https://` syntax), but in addition, the [ml.nrel.gov](https://ml.nrel.gov) site might not be the correct one. Was it intended to be `[bde.ml.nrel.gov](https://bde.ml.nrel.gov/)`? I.e., [this website](https://bde.ml.nrel.gov/)?

**Comment by pstjohn** [comment]
Thanks for the catch! It used to be ml.nrel.gov, but you're right that we moved it to bde.ml.nrel.gov
