### ISSUE TITLE
verbose is not working

### ISSUE THREAD

**Issue by LuckyLittleMonster** [NREL/alfabet#11]
>>> mol_good = "Cc1ccccc1O"
>>> model.predict([mol_good], verbose=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: predict() got an unexpected keyword argument 'verbose'

**Comment by pstjohn** [comment]
This should be fixed in the HEAD branch, but will require another release before it's fixed in the pip-installed version. I'll wait for a bit on #12 to see if we can bundle those two fixes together
